plot(x, type="b")
points(y)
lines(y)
pulll <- c(3,3)
pushh <- c(8,10)
lines(pulll,pushh)
pulll4 <- c(4,4)
pushh4 <- c(4,11)
polygon(c(pulll,pulll4,pulll5), c(pushh,pushh4,pushh5), col="orange", border="red")
lines(pulll4, pushh4)
pulll5 <- c(5,5)
pushh5 <- c(1,12)
lines(pulll5, pushh5)
